- type: job
  id: MailCarrier
  name: job-name-mail-carrier
  description: job-description-mail-carrier
  startingGear: MailCarrierGear
  playTimeTracker: JobMailCarrier
  icon: "JobIconMailCarrier"
  supervisors: job-supervisors-qm
  access:
  - Cargo
  - Maintenance
  - Mail

- type: startingGear
  id: MailCarrierGear
  equipment:
    head: ClothingHeadCourier # DeltaV - New courier look
    jumpsuit: ClothingUniformCourier # DeltaV - New courier look
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBlack
    id: MailCarrierPDA
    ears: ClothingHeadsetCargo
    belt: CourierBag # DeltaV - New courier look
  innerclothingskirt: ClothingUniformSkirtCourier # DeltaV - New courier look
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
