- type: job
  id: AdministrativeAssistant
  name: job-name-admin-assistant
  description: job-description-admin-assistant
  playTimeTracker: JobAdminAssistant
  requirements:
    - !type:DepartmentTimeRequirement
      department: Command
      time: 21600 # 6 hours
    - !type:OverallPlaytimeRequirement 
      time: 36000 # 10 hours
    - !type:WhitelistRequirement
  weight: 20
  startingGear: AdminAssistantGear
  icon: "JobIconAdminAssitant"
  joinNotifyCrew: true
  supervisors: job-supervisors-command
  canBeAntag: false
  access:
  - Command
  - Maintenance
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

- type: startingGear
  id: AdminAssistantGear
  equipment:
    shoes: ClothingShoesBootsLaceup
    belt: BoxFolderClipboard
    id: AdminAssistantPDA
    ears: ClothingHeadsetAltAdminAssistant