- type: gameMapPool
  id: DefaultMapPool
  maps:
  #- Aspid
  #- Bagel
  #- Barratry
  #- Box
  #- Cluster
  #- Core
  #- Fland
  #- Kettle
  #- Marathon
  #- Meta
  #- Omega
  #- Origin
  #- Saltern
  #- Packed
# DeltaV - keep it alphabetized or I'll stab you
  - Arena
  - Asterisk
  - Edge
  - Pebble
  - Submarine
  - Tortuga
