- type: job
  id: Fugitive
  name: job-name-fugitive
  description: job-description-fugitive
  playTimeTracker: JobFugitive
  startingGear: FugitiveStartingGear
  setPreference: false
  icon: "JobIconPrisoner"

- type: antag
  id: Fugitive
  name: roles-antag-fugitive-name
  antagonist: true
  setPreference: false
  objective: roles-antag-fugitive-objective

- type: startingGear
  id: FugitiveStartingGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    gloves: ClothingHandsGlovesColorYellow
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
  inhand:
    - ToolboxElectricalFilled
  innerClothingSkirt: ClothingUniformJumpskirtPrisoner
