- type: quickPhrase
  id: BaseCivilianPhrase
  group: Civilian
  abstract: true

- type: quickPhrase
  id: BaseCommandPhrase
  group: Command
  styleClass: CommandButton
  abstract: true

- type: quickPhrase
  id: BaseEngineeringPhrase
  group: Engineering
  styleClass: EngineeringButton
  abstract: true

- type: quickPhrase
  id: BaseEpistemicsPhrase
  group: Epistemics
  styleClass: EpistemicsButton
  abstract: true

- type: quickPhrase
  id: BaseLogisticsPhrase
  group: Logistics
  styleClass: LogisticsButton
  abstract: true

- type: quickPhrase
  id: BaseMedicalPhrase
  group: Medical
  styleClass: MedicalButton
  abstract: true

- type: quickPhrase
  id: BaseSecurityPhrase
  group: Security
  styleClass: SecurityButton
  abstract: true

- type: quickPhrase
  id: BaseServicePhrase
  group: Service
  styleClass: ServiceButton
  abstract: true