- type: quickPhrase
  id: BaseCivilianPhrase
  group: Civilian
  color: "#9FED58"
  abstract: true

- type: quickPhrase
  id: BaseCommandPhrase
  group: Command
  color: "#334E6D"
  abstract: true

- type: quickPhrase
  id: BaseEngineeringPhrase
  group: Engineering
  color: "#EFB341"
  abstract: true

- type: quickPhrase
  id: BaseEpistemicsPhrase
  group: Epistemics
  color: "#D381C9"
  abstract: true

- type: quickPhrase
  id: BaseLogisticsPhrase
  group: Logistics
  color: "#A46106"
  abstract: true

- type: quickPhrase
  id: BaseMedicalPhrase
  group: Medical
  color: "#52B4E9"
  abstract: true

- type: quickPhrase
  id: BaseSecurityPhrase
  group: Security
  color: "#DE3A3A"
  abstract: true

- type: quickPhrase
  id: BaseServicePhrase
  group: Service
  color: "#9FED58"
  abstract: true