# Created From Coder Socks as Base for texturing
# Made By NeptuneZvezda on Discord

- type: entity
  parent: ClothingShoesBase
  id: Socks_Striped_Security.rsi
  name: Security striped socks
  description: These striped socks make you feel like beating a mime
  components:
  - type: Sprite
    sprite: Clothing\Under\Socks\Socks_Striped_Security.rsi
  - type: Clothing
    sprite: Clothing\Under\Socks\Socks_Striped_Security.rsi


