- type: job
  id: ArmoryCommander
  parent: Warden
  name: job-name-armory-commander
  description: job-description-armory-commander
  playTimeTracker: JobArmoryCommander
  startingGear: ArmoryCommanderGear
  icon: "JobIconWarden" #here???

- type: startingGear
  id: ArmoryCommanderGear
  equipment:
    head: ClothingHeadHatWarden  #here
    jumpsuit: ClothingUniformJumpsuitWarden  #here
    back: ClothingBackpackSecurityFilled
    shoes: ClothingShoesBootsCombatFilled
    eyes: ClothingEyesGlassesSecurity
    outerClothing: ClothingOuterCoatWarden  #here
    id: WardenPDA  #here
    ears: ClothingHeadsetSecurity
    belt: ClothingBeltSecurityFilled
    pocket1: WeaponPistolMk58Nonlethal
  innerClothingSkirt: ClothingUniformJumpskirtWarden  #here
  satchel: ClothingBackpackSatchelSecurityFilled
  duffelbag: ClothingBackpackDuffelSecurityFilled
