- type: job
  id: Brigmedic
  name: job-name-brigmedic
  description: job-description-brigmedic
  playTimeTracker: JobBrigmedic
  requirements:
    - !type:DepartmentTimeRequirement
      department: Medical
      time: 21600 # 6 hrs
    - !type:DepartmentTimeRequirement
      department: Security
      time: 18000 # 4 hrs
  startingGear: BrigmedicGear
  icon: "JobIconBrigmedic"
  supervisors: job-supervisors-hos
  canBeAntag: false
  access:
  - Medical
  - Security
  - Brig
  - Maintenance
  - External
  special:
  - !type:AddImplantSpecial
    implants: [ MindShieldImplant ]

## see Prototypes/Roles/Jobs/Fun/misc_startinggear.yml
#- type: startingGear
#  id: BrigmedicGear
#  equipment:
#    jumpsuit: ClothingUniformJumpsuitBrigmedic
#    outerClothing: ClothingOuterCoatAMG
#    back: ClothingBackpackBrigmedicFilled
#    shoes: ClothingShoesColorRed
#    gloves: ClothingHandsGlovesNitrile
#    eyes: ClothingEyesHudMedical
#    head: ClothingHeadHatBeretBrigmedic
#    id: BrigmedicPDA
#    ears: ClothingHeadsetBrigmedic
#    mask: ClothingMaskBreathMedicalSecurity
#    belt: ClothingBeltMedicalFilled
#  innerclothingskirt: ClothingUniformJumpskirtBrigmedic
#  satchel: ClothingBackpackSatchelBrigmedicFilled
#  duffelbag: ClothingBackpackDuffelBrigmedicFilled
