# Base Nyano Mail
- type: entity
  parent: BaseMail
  id: MailSecurityDonuts
  suffix: donuts
  components:
  - type: Mail
    contents:
    - id: FoodBoxDonut

- type: entity
  parent: BaseMail
  id: MailSecurityFlashlight
  suffix: seclite
  components:
  - type: Mail
    contents:
    - id: FlashlightSeclite

- type: entity
  parent: BaseMail
  id: MailSecurityNonlethalsKit
  suffix: nonlethalskit
  components:
  - type: Mail
    contents:
    - id: Flash
      maxAmount: 2
    - id: GrenadeFlashBang
      maxAmount: 2
    - id: Handcuffs
      maxAmount: 2

#- type: entity
#  parent: BaseMail
#  id: MailSecuritySpaceLaw
#  suffix: spacelaw
#  components:
#  - type: Mail
#    contents:
#    - id: HyperlinkBookSpaceLaw
# Will we ever readd hyperlinks books? Who knows!

- type: entity
  parent: BaseMail
  id: MailWardenCrowdControl
  suffix: crowdcontrol
  components:
  - type: Mail
    contents:
    - id: BoxBeanbag

- type: entity
  parent: BaseMail
  id: MailDetectiveForensicSupplement # Deltav - Detective is in charge of investigating crimes.
  suffix: detectivesupplement # Deltav - Detective is in charge of investigating crimes.
  components:
  - type: Mail
    contents:
    - id: BoxForensicPad

# Frontier Mail

- type: entity
  noSpawn: true
  parent: BaseMailLarge
  id: MailSecurityNFMusket
  suffix: musket
  components:
  - type: Mail
    contents:
    - id: ClothingHeadHatPwig
    - id: Musket
    - id: CartridgeAntiMateriel
      amount: 2
    - id: PaperMailNTMusket