# Delta-V - This file is licensed under AGPLv3
# Copyright (c) 2024 Delta-V Contributors
# See AGPLv3.txt for details.

- type: playTimeTracker
  id: JobBrigmedic

- type: playTimeTracker
  id: JobMedicalBorg
